---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: content/about
  label: About
  create: all
  default_front_matter_template: about
- path: content/posts
  label: Posts
  create: all
  default_front_matter_template: posts
- path: content
  label: Pages
  create: all
upload_dir: forestryio/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.17'
