---
upload_path: "/forestryio/images"
frontmatter_file_url_template: 
body_file_url_template: 
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  posts:
    default_front_matter_template: posts
  about:
    default_front_matter_template: about
version: '0.17'
